use_default_settings: true

general:
  instance_name: "NLP Workflow Search"

search:
  default_lang: "en"

server:
  secret_key: "nlp-workflow-secret-key-change-this-in-production"
  public_instance: true
  limiter: false

engines:
  - name: arxiv
    disabled: false
  - name: duckduckgo  
    disabled: false
